spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batchProcessing
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true


  batch:
    jdbc:
      initialize-schema: ALWAYS
